views:
  - name: vw_credit_card_transactions
    
    cubes:

      - join_path: credit_card_transactions
        prefix: false
        includes:
          # dimensions
          - spend_date
          # measures
          - total_spend

      - join_path: credit_card_transactions.credit_card_credit_risk
        prefix: false
        includes:
          - credit_risk_bin_cc
          - account_approval_date_cc
          - line_assignment_segment_cc
          - delinquency_bin_cc
          - revolve_status_cc
