views:
  - name: vw_credit_card_funnel_cohort_based
    
    cubes:

      - join_path: credit_card_funnel_cohort_based
        prefix: false
        includes:
          # dimensions
          - invitation_created_at
          # measures
          - invitations_sent
          - applications_submitted
          - applications_approved
          - applications_denied
