views:
  - name: vw_credit_card_rewards
    
    cubes:

      - join_path: credit_card_rewards
        prefix: false
        includes:
          # dimensions
          - created_at
          # measures
          - credit_card_rewards_accrued

      - join_path: credit_card_rewards.businesses
        prefix: false
        includes:
          # Dimensions
          - opened_account_cohort
          - business_type
          - business_industry_category
          - b2b_services_flag
          - age_of_business
          - tenure
