views:
  - name: vw_boosts_activity
    
    cubes:

      - join_path: boosts_activity
        prefix: false
        includes:
          # dimensions
          - boost_created_at
          # measures
          - boost_attach
          - boost_active

      - join_path: boosts_activity.businesses
        prefix: false
        includes:
          # Dimensions
          - opened_account_cohort
          - business_type
          - business_industry_category
          - b2b_services_flag
          - age_of_business
          - tenure
